Doc page for Heading component
dxc-technology/halstack-style-guide pull request #784
Opened 2022-03-08 09:46 UTC by Lisa159

2022-03-09 08:35 UTC, aweell commented
The latest changes for the heading component weren't merged in master from 4.2.0 (including the changes in the levels `font-size`)

The updated documentation can be found in https://github.com/dxc-technology/halstack-style-guide/tree/4.2.0/guidelines/components/heading

2022-03-09 16:23 UTC, raquelarrojo requested changes

2022-03-11 11:22 UTC, Lisa159 commented on website/pages/components/header/index.tsx
> +  return <HeadingPageLayout>{page}</HeadingPageLayout>;
Missclick, I was changing heading and looks like I changed header. I will revert it.

2022-03-11 11:34 UTC, Lisa159 commented on website/pages/components/header/index.tsx
> +  return <HeadingPageLayout>{page}</HeadingPageLayout>;
Done.

2022-03-11 11:34 UTC, Lisa159 commented on website/screens/components/heading/usage/HeadingUsagePage.tsx
> +        </DxcText>
Done.

2022-03-11 11:34 UTC, Lisa159 commented on website/screens/components/heading/usage/HeadingUsagePage.tsx
> +        <HeadingLink level={3}>Do&#39;s</HeadingLink>
Done.

2022-03-11 11:34 UTC, Lisa159 commented on website/screens/components/heading/usage/HeadingUsagePage.tsx
> +        <DxcList>
Done.

2022-03-11 11:34 UTC, Lisa159 commented on website/screens/components/heading/usage/HeadingUsagePage.tsx
> +        <HeadingLink level={3}>Dont&#39;s</HeadingLink>
Done.

2022-03-11 12:21 UTC, Lisa159 commented
> The latest changes for the heading component weren't merged in master from 4.2.0 (including the changes in the levels `font-size`)
> 
> The updated documentation can be found in https://github.com/dxc-technology/halstack-style-guide/tree/4.2.0/guidelines/components/heading

@aweell Updated Heading with version 4.2.0.

2022-03-11 12:37 UTC, raquelarrojo approved these changes

2022-03-11 12:37 UTC, merged